version: '3'

services:
  nuxt:
    container_name: shopping-list

    # Dockerfileの場所
    build:
      context: ./
      dockerfile: Dockerfile
    tty: true
    stdin_open: true

    # コンテナ起動時のコマンド
    # 初回起動時は時間がかかる
    working_dir: /app
    
    # ホストOSとコンテナ内でソースコードを共有
    # node_modulesは除外
    volumes:
      - .:/app
      - /app/node_modules
    # コンテナ内部3000を外部から4000でアクセス

    ports:
      - "4000:3000"
    command: yarn dev
